### ISSUE TITLE
does not work for some .wpl

### ISSUE THREAD

**Issue by jonhp** [UrbanCMC/foo_wpl#2]
cannot find any of the music files even though they exist. this is a valid .wpl constructed file.

`<?wpl version="1.0"?>
<smil>
    <head>
        <meta name="Generator" content="Microsoft Windows Media Player -- 12.0.7601.17514"/>
        <meta name="ItemCount" content="62"/>
        <meta name="IsFavorite"/>
        <meta name="ContentPartnerListID"/>
        <meta name="ContentPartnerNameType"/>
        <meta name="ContentPartnerName"/>
        <meta name="Subtitle"/>
        <author/>
        <title>Elton John 21st</title>
    </head>
    <body>
        <seq>
            <media src="..\Elton John\The Road to El Dorado\01 El Dorado.wma" cid="{B1B4E213-1074-4204-8036-2B24E9F40AD9}" tid="{3C30F4DE-6342-4F92-AF73-7E8BE9D7B01E}"/>
            <media src="..\Elton John\The Road to El Dorado\02 Someday Out of the Blue [Theme from el Dorado].wma" cid="{93516E93-C788-4054-B982-F4371AD67F03}" tid="{BA64E693-BE71-452D-9859-BF6B171FE073}"/>
            <media src="..\Elton John\The Road to El Dorado\03 Without Question.wma" cid="{8E8E7D4C-5DC7-4508-B17A-2B31B0249A7A}" tid="{530F79C6-3E87-44A5-97B8-CB1FAD5185B6}"/>
            <media src="..\Elton John\The Road to El Dorado\04 Friends Never Say Goodbye.wma" cid="{99499791-97C3-47D2-A5FF-A9BD08F11CAB}" tid="{5DEBB640-70D0-457D-AA64-2127EA2E3CC0}"/>
            <media src="..\Elton John\The Road to El Dorado\05 The Trail We Blaze.wma" cid="{5ED96130-27DF-45C2-BF72-BAEB8A1DA167}" tid="{E13A5318-0339-48E3-B9C2-F35FDD898B3B}"/>
            <media src="..\Elton John\The Road to El Dorado\06 16th Century Man.wma" cid="{D1133A2B-82E6-40A1-9750-6BB89EBCD7F2}" tid="{772038B5-31D5-447D-9CFF-E25A0A8A3E0D}"/>
            <media src="..\Elton John\The Road to El Dorado\07 The Panic in Me.wma" cid="{795D7034-CBF6-45C8-86E8-0D16BF5201F5}" tid="{C2B8B130-8E41-4E28-82B0-0605B4A7109F}"/>
            <media src="..\Elton John\The Road to El Dorado\08 It&apos;s Tough to Be a God.wma" cid="{29012D7A-682B-4371-A5DE-65053E6A6DF2}" tid="{A54B1FF0-5F22-4078-B185-FB442F77B09B}"/>
            <media src="..\Elton John\The Road to El Dorado\09 Trust Me.wma" cid="{FFC08718-623D-41B4-A673-384BDB3FCC04}" tid="{0E3FE748-765A-4389-894F-278547B22ECD}"/>
            <media src="..\Elton John\The Road to El Dorado\10 My Heart Dances.wma" cid="{5CF5A816-DBBB-40D1-8753-A367F2C9485B}" tid="{4FF394C6-2ED6-409D-9045-D746CB038ED4}"/>
            <media src="..\Elton John\The Road to El Dorado\11 Queen of Cities.wma" cid="{6FAB5341-C218-45AF-A295-1EECDEF91857}" tid="{B823AF63-FAC1-474B-B59E-42FFC7C86FF9}"/>
            <media src="..\Elton John\The Road to El Dorado\12 Cheldorado.wma" cid="{0ABF8C9F-B224-428B-9075-41F2E974CE57}" tid="{60146A07-7CE2-4986-88E5-9170B83F2FCC}"/>
            <media src="..\Elton John\The Road to El Dorado\13 The Brig.wma" cid="{9256E868-6540-4696-891C-535B5CE86DCC}" tid="{367CD109-F4D7-455B-95DD-0F92E2BC50E9}"/>
            <media src="..\Elton John\The Road to El Dorado\14 Wonders of the New World.wma" cid="{84739F89-890F-4D95-A5AE-B23466A56154}" tid="{184DEDD7-FF1F-4C15-8614-08A409CC6506}"/>
            <media src="..\Elton John\Songs from the West Coast\01 The Emperor&apos;s New Clothes.wma" cid="{83EBDC05-1A4C-4834-98C9-CC4517A7728E}" tid="{27D83DA0-C587-4C59-8475-8F59DF84A2AD}"/>
            <media src="..\Elton John\Songs from the West Coast\02 Dark Diamond.wma" cid="{72E63AF3-7185-4C67-916C-85CD31E0915C}" tid="{0A11CBE1-1FF3-4522-9899-B692F0E49F4F}"/>
            <media src="..\Elton John\Songs from the West Coast\03 Look Ma, No Hands.wma" cid="{5C6B8AEB-7C23-4856-97FF-65A73630749C}" tid="{57DE21E3-DACB-4522-881B-126B25CC3A1D}"/>
            <media src="..\Elton John\Songs from the West Coast\04 American Triangle.wma" cid="{DCC397F2-8495-4173-B892-78480F2A71A9}" tid="{A4685AA9-5B4E-4306-81F9-3F40ADC8C3DF}"/>
            <media src="..\Elton John\Songs from the West Coast\05 Original Sin.wma" cid="{03461B13-0635-4317-B3F3-7C1EAED90D56}" tid="{C979794C-0C14-4739-A2D3-315B6BF23934}"/>
            <media src="..\Elton John\Songs from the West Coast\06 Birds.wma" cid="{63FC428F-4300-42E9-95CE-BB737B5B8833}" tid="{A66A116C-04FB-4597-AD35-0BF8B2E1D023}"/>
            <media src="..\Elton John\Songs from the West Coast\07 I Want Love.wma" cid="{BFFC1655-48EA-4F6B-8D97-3C78663928E4}" tid="{27B2BD45-B04E-4577-9000-C4EA3350E42E}"/>
            <media src="..\Elton John\Songs from the West Coast\08 The Wasteland.wma" cid="{7C78CF2B-B1AD-46B4-BC9B-E4CDD8EA26F1}" tid="{B59A36AB-A160-49A3-81D1-B702327E203F}"/>
            <media src="..\Elton John\Songs from the West Coast\09 Ballad of the Boy in the Red Shoes.wma" cid="{9EAF339B-8CC1-400F-B27D-42430AA5653C}" tid="{3C734705-D319-422D-BAF3-7941C2CECD9E}"/>
            <media src="..\Elton John\Songs from the West Coast\10 Love Her Like Me.wma" cid="{9EAEAB3D-443D-4726-AE3D-F93488C6557D}" tid="{D9FFA179-764F-48EB-B975-8E0D437F6A23}"/>
            <media src="..\Elton John\Songs from the West Coast\11 Mansfield.wma" cid="{B8BE9CB7-860E-4ED1-AB5B-69AC349A5C14}" tid="{D489EDA7-E89B-418E-9B9B-8340539C2A3D}"/>
            <media src="..\Elton John\Songs from the West Coast\12 This Train Don&apos;t Stop There Anymore.wma" cid="{9AACF6C1-4B44-4766-8804-38B7CD803F6E}" tid="{47A38358-68D5-4C11-A86C-3EFA8B4030C9}"/>
            <media src="..\Elton John\Peachtree Road\01 Weight of the World.wma" cid="{50964E9F-DE92-41FE-AFD3-5C0823D62B07}" tid="{6291722D-965C-4EA3-97CF-4956B7E258C2}"/>
            <media src="..\Elton John\Peachtree Road\02 Porch Swing in Tupelo.wma" cid="{45040DB0-5F8E-42E9-A0E7-BC476F8E71AF}" tid="{B2C4A227-8D72-4D23-9087-3FF065DC61AC}"/>
            <media src="..\Elton John\Peachtree Road\03 Answer in the Sky.wma" cid="{D03B9562-C891-47AF-AA57-4CC3A4AE36B4}" tid="{F923DD87-1377-4ABC-8B18-DAF3B44C2874}"/>
            <media src="..\Elton John\Peachtree Road\04 Turn the Lights Out When You Leave.wma" cid="{A421FB46-1DF3-4587-85F5-C2943D49E35F}" tid="{F85A2269-477D-4EBA-8265-F5300A025D3D}"/>
            <media src="..\Elton John\Peachtree Road\05 My Elusive Drug.wma" cid="{15D75603-ABE1-4488-B2E7-163683445401}" tid="{1FEC33AE-8B71-4514-8575-19B1B85D9E58}"/>
            <media src="..\Elton John\Peachtree Road\06 They Call Her the Cat.wma" cid="{71BD7C34-0F81-477B-AB73-A1E456227186}" tid="{41088E8B-93DF-4B70-BDC7-1F7295D3A29B}"/>
            <media src="..\Elton John\Peachtree Road\07 Freaks in Love.wma" cid="{4BF94D80-B29F-4BF9-BB0F-0C4800D23704}" tid="{105C000B-90C9-499E-AA35-43F7D631FC6A}"/>
            <media src="..\Elton John\Peachtree Road\08 All That I&apos;m Allowed.wma" cid="{9F34827F-7D27-4FE6-BE71-1EDA677DDDF5}" tid="{BD783B50-B868-43E1-B854-424B329650F7}"/>
            <media src="..\Elton John\Peachtree Road\09 I Stop and I Breathe.wma" cid="{B4CF00AB-9A59-4056-9EE3-0D984FACCAC9}" tid="{A1EFF613-A190-4B20-82B5-299088422420}"/>
            <media src="..\Elton John\Peachtree Road\10 Too Many Tears.wma" cid="{27FAEB2F-8B3B-468E-9565-321C5A42DB03}" tid="{8035A8DE-F9FF-4344-9359-2CE46D4AC4EE}"/>
            <media src="..\Elton John\Peachtree Road\11 It&apos;s Getting Dark in Here.wma" cid="{A8D11BF4-B90E-4FC2-A72A-2ACD60FFE503}" tid="{2954900D-03F6-470D-B7BE-30CBC1E0F088}"/>
            <media src="..\Elton John\Peachtree Road\12 I Can&apos;t Keep This from You.wma" cid="{8F64DC51-3DE2-490F-930E-2D4AE6726128}" tid="{1AF55746-EFA3-4E61-B7F6-5E7D592DF7C2}"/>
            <media src="..\Elton John\The Captain &amp; the Kid\01 Postcards from Richard Nixon.wma" cid="{D6B9452E-5315-4DC8-9D5C-E03371955FB3}" tid="{7CC2A8CE-5703-470E-AE06-C14B8E4ED535}"/>
            <media src="..\Elton John\The Captain &amp; the Kid\02 Just Like Noah&apos;s Ark.wma" cid="{3A357A16-5E2E-4473-B583-90022E9FED6F}" tid="{E89E7A6F-1E57-4623-AD28-253017F8A6B0}"/>
            <media src="..\Elton John\The Captain &amp; the Kid\03 Wouldn&apos;t Have You Any Other Way (NYC).wma" cid="{A823E4AA-4C75-4DB4-BBF1-7BFEF02A2608}" tid="{959E8E47-85D5-4986-81C3-770DC41E3604}"/>
            <media src="..\Elton John\The Captain &amp; the Kid\04 Tinderbox.wma" cid="{9C29CCD6-4352-4FC0-81FC-DE51FF41401D}" tid="{F0844C2D-2698-466F-833D-ADA169BFFA07}"/>
            <media src="..\Elton John\The Captain &amp; the Kid\05 And the House Fell Down.wma" cid="{39C346CC-EC06-4BC7-8E5F-BC97EFD2A42F}" tid="{5442C1A1-364A-4F8F-B3B5-69549E6FB106}"/>
            <media src="..\Elton John\The Captain &amp; the Kid\06 Blues Never Fade Away.wma" cid="{5CEA9967-9E7E-4775-8C6B-8C55473F0340}" tid="{3841C9FC-C26A-4823-9B9E-8C2EB3001236}"/>
            <media src="..\Elton John\The Captain &amp; the Kid\07 The Bridge.wma" cid="{3ED40BCE-6BE6-4B19-B896-FB97072810EE}" tid="{A4688C8C-6531-4390-8F54-249716DBD6F8}"/>
            <media src="..\Elton John\The Captain &amp; the Kid\08 I Must Have Lost It on the Wind.wma" cid="{DBFAE816-03C1-42FE-8DA6-BC2E68783110}" tid="{747EA548-60E1-4377-8841-6C2B7D8B3513}"/>
            <media src="..\Elton John\The Captain &amp; the Kid\09 Old 67.wma" cid="{EC9CA404-1055-46BA-83CB-5C3C691E12C6}" tid="{90CC81BD-24D2-4068-9706-8380A880A9D9}"/>
            <media src="..\Elton John\The Captain &amp; the Kid\10 The Captain and the Kid.wma" cid="{540FAEE3-EAC3-4EE9-91D3-9D56B778B775}" tid="{7F0F8E8A-CA84-4F7B-9EB3-2903D50AB3CC}"/>
            <media src="..\Elton John-Leon Russell\The Union\01 If It Wasn&apos;t for Bad.wma" cid="{C021AB4B-6128-4DE2-8243-FBC8CC01A4F7}" tid="{16C6748C-9EFA-4247-8127-1EA426438C9D}"/>
            <media src="..\Elton John-Leon Russell\The Union\02 Eight Hundred Dollar Shoes.wma" cid="{4CEB3471-4CE5-4984-9988-96CA1815460A}" tid="{DAEAF168-C331-423C-99E2-FCA7830AFAD3}"/>
            <media src="..\Elton John-Leon Russell\The Union\03 Hey Ahab.wma" cid="{96FA9FC7-9F10-4D4D-BDF6-ADF769D89748}" tid="{C33D51F9-BDAB-4C8B-9FA5-F7CB2D321C5C}"/>
            <media src="..\Elton John-Leon Russell\The Union\04 Gone to Shiloh.wma" cid="{FCBBA19C-4B8E-4F90-9EA4-151D97A25354}" tid="{1F00F864-6297-43C8-B796-1F4FD9D8DA2F}"/>
            <media src="..\Elton John-Leon Russell\The Union\05 Jimmie Rodgers&apos; Dream.wma" cid="{D2ACD2AD-7CD3-43D8-A946-9A2D6FE266A9}" tid="{4200F63A-BA16-4AAF-B602-5D5A9EC0A347}"/>
            <media src="..\Elton John-Leon Russell\The Union\06 There&apos;s No Tomorrow.wma" cid="{61D9A35D-EBAC-4312-A84B-BA34A270CA45}" tid="{E665C7B9-1C2A-4209-939C-28797DF260F2}"/>
            <media src="..\Elton John-Leon Russell\The Union\07 Monkey Suit.wma" cid="{EBC27A48-A1B5-4890-8959-D67E19C58428}" tid="{5DFE95FA-A2EF-4BE0-8FD8-8131F030062A}"/>
            <media src="..\Elton John-Leon Russell\The Union\08 The Best Part of the Day.wma" cid="{A783DF1C-C666-4941-9C85-4725435F7F0C}" tid="{7B356258-C9DA-4440-8AA2-95D3495D9EAD}"/>
            <media src="..\Elton John-Leon Russell\The Union\09 A Dream Come True.wma" cid="{20CE839C-A7A9-4013-B605-EE26783C1C2B}" tid="{F76F50A0-F211-4336-A292-06576895FDF8}"/>
            <media src="..\Elton John-Leon Russell\The Union\10 When Love Is Dying.wma" cid="{DC49081C-C194-4040-AACE-F883C6F8C2EF}" tid="{E7470EA1-C2D5-4EFE-96E7-07FD5053709A}"/>
            <media src="..\Elton John-Leon Russell\The Union\11 I Should Have Sent Roses.wma" cid="{8C253D34-71BD-465A-A86D-4905E33720FF}" tid="{8495E21C-E0E6-4740-A32C-0CC1CD8D646D}"/>
            <media src="..\Elton John-Leon Russell\The Union\12 Hearts Have Turned to Stone.wma" cid="{FCE5761A-0503-468B-8C1C-A26766B09162}" tid="{6C5353FF-C9D7-474E-994C-1E1FDEE45576}"/>
            <media src="..\Elton John-Leon Russell\The Union\13 Never Too Old (To Hold Somebody).wma" cid="{3A3DAFE9-F17E-474D-BD9C-86A4473800BD}" tid="{AEC0D851-7C56-454F-8163-EAF507C4179D}"/>
            <media src="..\Elton John-Leon Russell\The Union\14 In the Hands of Angels.wma" cid="{8FF77B52-3DD3-424A-BB91-336809045B22}" tid="{768085A1-0A35-42B0-B5A8-C4AC89383125}"/>
            <media src="..\Elton John\Diving Board [Deluxe Edition]\01 Oceans Away.wma"/>
            <media src="..\Elton John\Diving Board [Deluxe Edition]\02 Oscar Wilde Gets Out.wma"/>
            <media src="..\Elton John\Diving Board [Deluxe Edition]\03 A Town Called Jubilee.wma"/>
            <media src="..\Elton John\Diving Board [Deluxe Edition]\04 The Ballad of Blind Tom.wma"/>
            <media src="..\Elton John\Diving Board [Deluxe Edition]\05 Dream, Pt. 1.wma"/>
            <media src="..\Elton John\Diving Board [Deluxe Edition]\06 My Quicksand.wma"/>
            <media src="..\Elton John\Diving Board [Deluxe Edition]\07 Can&apos;t Stay Alone Tonight.wma"/>
            <media src="..\Elton John\Diving Board [Deluxe Edition]\08 Voyeur.wma"/>
            <media src="..\Elton John\Diving Board [Deluxe Edition]\09 Home Again.wma"/>
            <media src="..\Elton John\Diving Board [Deluxe Edition]\10 Take This Dirty Water.wma"/>
            <media src="..\Elton John\Diving Board [Deluxe Edition]\11 Dream, Pt. 2.wma"/>
            <media src="..\Elton John\Diving Board [Deluxe Edition]\12 The New Fever Waltz.wma"/>
            <media src="..\Elton John\Diving Board [Deluxe Edition]\13 Mexican Vacation (Kids in the Candlelight).wma"/>
            <media src="..\Elton John\Diving Board [Deluxe Edition]\14 Dream, Pt. 3.wma"/>
            <media src="..\Elton John\Diving Board [Deluxe Edition]\15 The Diving Board.wma"/>
            <media src="..\Elton John\Diving Board [Deluxe Edition]\16 Candlelit Bedroom [-].wma"/>
            <media src="..\Elton John\Diving Board [Deluxe Edition]\17 Home Again [-][Live][Live from Capitol Studio 2013].wma"/>
            <media src="..\Elton John\Diving Board [Deluxe Edition]\18 Mexican Vacation (Kids in the Candlelight) [Live from Capitol Studio 20.wma"/>
            <media src="..\Elton John\Diving Board [Deluxe Edition]\19 The New Fever Waltz [-][Live][Live from Capitol Studio 2013].wma"/>
            <media src="..\Elton John\Wonderful Crazy Night\01 Wonderful Crazy Night.flac"/>
            <media src="..\Elton John\Wonderful Crazy Night\02 In The Name Of You.flac"/>
            <media src="..\Elton John\Wonderful Crazy Night\03 Claw Hammer.flac"/>
            <media src="..\Elton John\Wonderful Crazy Night\04 Blue Wonderful.flac"/>
            <media src="..\Elton John\Wonderful Crazy Night\05 I've Got 2 Wings.flac"/>
            <media src="..\Elton John\Wonderful Crazy Night\06 A Good Heart.flac"/>
            <media src="..\Elton John\Wonderful Crazy Night\07 Looking Up.flac"/>
            <media src="..\Elton John\Wonderful Crazy Night\08 Guilty Pleasure.flac"/>
            <media src="..\Elton John\Wonderful Crazy Night\09 Tambourine.flac"/>
            <media src="..\Elton John\Wonderful Crazy Night\10 The Open Chord.flac"/>
            <media src="..\Elton John\Wonderful Crazy Night\11 Free And Easy.flac"/>
            <media src="..\Elton John\Wonderful Crazy Night\12 England And America.flac"/>
            <media src="..\Elton John\Wonderful Crazy Night\13 Looking Up (Live).flac"/>
            <media src="..\Elton John\Wonderful Crazy Night\14 Wonderful Crazy Night (Live).flac"/>
        </seq>
    </body>
</smil>
`

**Comment by UrbanCMC** [comment]
Hi there and thank you for the report.

This actually isn't a problem with this plugin, but with foobar itself if you want, because it can't read files from the relative paths WMP uses. The only real option you have is to tell WMP to save your playlists to a different drive, and play them from there.

To do so, open your playlist in WMP and click the folder in the top-right corner, then select "Save list as..." and choose a drive other than the one your music is located on.
![wmp_save_playlist_as](https://cloud.githubusercontent.com/assets/9725089/15828961/cffe712c-2c11-11e6-92d8-13988d205f00.jpg)

I hope this allows you to resolve your issue.

**Comment by jonhp** [comment]
Hi,

Thanks for the response.

I am a foobar2k new user.

I am confused since this post seems to imply relative path support…

https://hydrogenaud.io/index.php/topic,109383.msg900575.html#msg900575 

jon

**Comment by UrbanCMC** [comment]
Hmm, looks like you're actually right.
It seems to be working the way it's supposed to with .m3u playlists.  

I'll try to get a new version out tomorrow that supports relative paths.

**Comment by jonhp** [comment]
Thanks very much. Jon

**Comment by UrbanCMC** [comment]
Your playlists should now work correctly when using [version 1.2](https://github.com/UrbanCMC/foo_wpl/releases/tag/v1.2).

**Comment by jonhp** [comment]
Hi thanks for the update.

We are getting closer.

It plays the first track on the playlist, then I get the same error as before:

Unable to open item for playback (Object not found):

"..\Elton John\Songs from the West Coast\04 American Triangle.wma"

jon

**Comment by UrbanCMC** [comment]
Yeah, I should probably have tested that with more than just one song.

It's working for me now with [version 1.2.1](https://github.com/UrbanCMC/foo_wpl/releases/tag/v1.2.1).

**Comment by jonhp** [comment]
Hi,

Now we’re talkin’, err Listening….

Thanks for the quick update….it is most appreciated. 

Jon
