### ISSUE TITLE
wpl plugin cannot correctly open urls or save playlists...

### ISSUE THREAD

**Issue by Zenith-Nadir** [UrbanCMC/foo_wpl#4]
Hi,
I am not sure if this project is still under development, however I would like to report some bugs I discovered.
I was thrilled to have foobar2000 plugin for .wpl lists. Thanks!

Issue#1: I have noticed if I create .wpl radio station url playlist, .wpl plugin appends automatically to the url (http://185.52.127.159/fr/30663/aac_64.mp3) absolute path of the .wpl playlist location and foobar2000 complaints:
Unable to open item for playback (Invalid path):
"\Folder1\Folder2\http://185.52.127.159/fr/30663/aac_64.mp3"
But foobar2000 has no problems opening m3u file with such urls.

Issue#2: .wpl plugin saves playlist changing the absolute file path to:
<media src="file://\Absolute_Path\
It appends "file:// to absolute path and foobar2000 again complaints: Unable to open item for playback (Invalid path):
Any chance to check these bugs (if they are really)?
Thanks
Z-N

**Comment by UrbanCMC** [comment]
Hi,
I'm always happy to hear someone is using my plugin, so thanks!

I'll of course take a look at both of those issues and try to fix them asap.

**Comment by Zenith-Nadir** [comment]
Thank you very much for your quick response.

I f I could be of any assistance, please, do not hesitate to contact me.

Also, one more suggestion: maybe you could add your plugin to foobar2000 repository, it would be so much easier to find it, and probably would get much more attention, since it is really a great tool.

Sincerely,

Z-N

**Comment by UrbanCMC** [comment]
You might want to give v1.2.2 a try.
I believe both of your issues should be fixed now.

**Comment by Zenith-Nadir** [comment]
Hi,

The problem with radio streams urls seems to be resolved. Thanks.

But the other problem: saving files' playlists still seems to persist; .wpl plugin still auto-adds prefix file:// to every absolute path of any file location, and foobar2000 does not like it (<media src="file://\NAS\Folder\file.ext)

Thank you for your assistance.

Sincerely,

Z-N

**Comment by UrbanCMC** [comment]
That's pretty odd.
I actually tested it on my own NAS and it worked perfectly fine.

Nevertheless, I completely removed the file:// part in v1.2.3, because it really isn't needed and other playlist-types don't use it either.

I hope this will resolve your problem.

**Comment by Zenith-Nadir** [comment]
Dear Sir (since I do not know how to address more personally),

THANK YOU!

It is working now.

Sincerely,

Z-N
